/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Recipe;
import dao.Step;
import taller1manejoderepositorios.Ingredient;
import taller1manejoderepositorios.Recipes;
import taller1manejoderepositorios.Taller1ManejodeRepositorios;

/**
 *
 * @author ADGS
 */
public class BuscarPorNombre extends javax.swing.JPanel {

    Recipes recipies = Taller1ManejodeRepositorios.recepies;
    /**
     * Creates new form buscarPorNombre
     */
    public BuscarPorNombre() {
        recipies.loadDefaultRecipes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        txtRecipeName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRecipe = new javax.swing.JTextArea();

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Busqueda por nombre de Receta");

        txtRecipeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecipeNameActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar...");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtAreaRecipe.setColumns(20);
        txtAreaRecipe.setRows(5);
        jScrollPane1.setViewportView(txtAreaRecipe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecipeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecipeNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRecipeNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Recipe recipeSeek =  this.recipies.seek(this.txtRecipeName.getText());
        if(recipeSeek != null){
            this.txtAreaRecipe.setText("");
            this.txtAreaRecipe.append("Id de La Receta : "  + recipeSeek.getiD() + "\n");
            this.txtAreaRecipe.append("Nombre de La Receta : "  + recipeSeek.getName() + "\n");
            this.txtAreaRecipe.append("\n Ingredientes de la Receta : \n");
            for(Ingredient e: recipeSeek.ingredients){
                this.txtAreaRecipe.append(" --- " + e.getName() + " --- " + e.getQuantity() + " gramos \n");
            }
            this.txtAreaRecipe.append("\n Pasos de la Receta : \n");
            for(Step e: recipeSeek.steps){
                this.txtAreaRecipe.append(" --- " + e.getId() + " --- " + e.getDescription() + " -- gramos \n");
            }
        }else
        {
            this.txtAreaRecipe.setText("");
            this.txtAreaRecipe.append("Lo sentimos no encontramos\n ninguna receta con su nombre");
        }

    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextArea txtAreaRecipe;
    private javax.swing.JTextField txtRecipeName;
    // End of variables declaration//GEN-END:variables
}
