/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GridBagConstraints;
import java.awt.Rectangle;
import javax.swing.JPanel;

/**
 *
 * @author ADGS
 */
public class run extends javax.swing.JFrame {

    /**
     * Creates new form run
     */
    public run() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itemCrearReceta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemPorIngrediente = new javax.swing.JMenuItem();
        itemPorNombre = new javax.swing.JMenuItem();
        itemBuscarNombreTiempo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recetario");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jMenu2.setText("Inicio");

        itemCrearReceta.setText("Crear Receta");
        itemCrearReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearRecetaActionPerformed(evt);
            }
        });
        jMenu2.add(itemCrearReceta);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Buscar");

        itemPorIngrediente.setText("Por Ingrediente");
        itemPorIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorIngredienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemPorIngrediente);

        itemPorNombre.setText("Por Nombre Receta");
        itemPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorNombreActionPerformed(evt);
            }
        });
        jMenu1.add(itemPorNombre);

        itemBuscarNombreTiempo.setText("Por Nombre o Tiempo");
        itemBuscarNombreTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarNombreTiempoActionPerformed(evt);
            }
        });
        jMenu1.add(itemBuscarNombreTiempo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCrearRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearRecetaActionPerformed
        
    }//GEN-LAST:event_itemCrearRecetaActionPerformed

    private void itemPorIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorIngredienteActionPerformed
        // TODO add your handling code here:
        BuscarPorIngrediente buscarPorIngredienteView = new BuscarPorIngrediente();
        buscarPorIngredienteView.setVisible(true);
        buscarPorIngredienteView.setBounds(new Rectangle(buscarPorIngredienteView.getPreferredSize()));
        this.contenedor.removeAll();
        this.contenedor.add(buscarPorIngredienteView);
        this.contenedor.updateUI();
    }//GEN-LAST:event_itemPorIngredienteActionPerformed

    private void itemPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorNombreActionPerformed
        // TODO add your handling code here:
        BuscarPorNombre buscarPorNombreView = new BuscarPorNombre();
        buscarPorNombreView.setVisible(true);
        buscarPorNombreView.setBounds(new Rectangle(buscarPorNombreView.getPreferredSize()));
        this.contenedor.removeAll();
        this.contenedor.add(buscarPorNombreView);
        this.contenedor.updateUI();
    }//GEN-LAST:event_itemPorNombreActionPerformed

    private void itemBuscarNombreTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarNombreTiempoActionPerformed
        // TODO add your handling code here:
        BuscarPorTiempoNombre buscarPortiempoNombre = new BuscarPorTiempoNombre();
        buscarPortiempoNombre.setVisible(true);
        buscarPortiempoNombre.setBounds(new Rectangle(buscarPortiempoNombre.getPreferredSize()));
        this.contenedor.removeAll();
        this.contenedor.add(buscarPortiempoNombre);
        this.contenedor.updateUI();
    }//GEN-LAST:event_itemBuscarNombreTiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new run().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem itemBuscarNombreTiempo;
    private javax.swing.JMenuItem itemCrearReceta;
    private javax.swing.JMenuItem itemPorIngrediente;
    private javax.swing.JMenuItem itemPorNombre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
